# Generated by Django 5.0.6 on 2024-07-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
